### ISSUE TITLE
What happened to the books.theunseen.city?

### ISSUE THREAD

**Issue by markwpoole** [bookwyrm-social/join-bookwyrm#131]
I’ve been using it for a while but sometime in the last few days it went offline. I don’t see it in your list of instances but it was one of the bigger ones. How to recover my history?

**Comment by mouse-reeve** [comment]
It appears to be up to me, are you still having trouble accessing it?

**Comment by markwpoole** [comment]
It was apparently down overnight, although I recently had further issues reaching it. I created a new account on Bookwyrm.social in the anticipation of moving across to it, but discovered that Bookwyrm exports don't contain enough data to even import into another Bookwyrm instance! Very disappointing, since I understood one of the benefits of the fediverse to be portability of your content. Even Mastodon doesn't support portability fully. It's easier to import Bookwyrm data back into Goodreads than it is to move between Bookwyrm instances. Sadly, this seems to be for decentralization enthusiasts but not robust enough for serious library management. Goodreads seems to be more "open" in its data formats than the "open source" Bookwyrm implementation. Staying with Goodreads for the foreseeable future. Cannot afford to provide data on thousands of books to Bookwyrm that I cannot fully retrieve unless I host my own instance.

**Comment by mouse-reeve** [comment]
Understood -- we are actively working on data export and account migration, but you're right that it's not sufficient right now, so I can see why it's not a good fit for you when that's still a pending feature.
