### ISSUE TITLE
Information about instances is updates manually, rather than automatically

### ISSUE THREAD

**Issue by aneverhopefulhelper** [bookwyrm-social/join-bookwyrm#59]
So I have noticed there is an inconsistency between the version of some instances such as wyrms.de and the version shown on the joinbookwyrm.com site, if you check here: https://wyrms.de/about it shows version 0.3.4, however on the https://joinbookwyrm.com/instances/ site it shows 0.3.0. Any idea why this is and if there is a fix?

Images for reference:
![Wyrms Correct](https://user-images.githubusercontent.com/91751074/164994981-bd15820f-edaf-4566-bab8-6d4143fd12f8.png)
![Join BookWyrm Incorrect](https://user-images.githubusercontent.com/91751074/164994984-bf3404c5-66a9-473b-8d5f-368a5768ff03.png)

**Comment by mouse-reeve** [comment]
Yep! Right now, the site is updated by me manually running a script, which isn't the best way for it to work 😄. At some point, the site should be updated to periodically update the instance list automatically

**Comment by aneverhopefulhelper** [comment]
> Yep! Right now, the site is updated by me manually running a script, which isn't the best way for it to work smile. At some point, the site should be updated to periodically update the instance list automatically

Thank you for explaining and hope you manage to get the automated soon, the manual way sounds like a pain for you, heh.

**Comment by msub2** [comment]
I briefly explored getting stats on page load with JavaScript, but I wasn't able to actually fetch the data due to CORS issues.

**Comment by mouse-reeve** [comment]
> I think the best way to go about this with minimal fuss might be to use a GitHub action that runs daily or weekly.

I didn't realize you can do this! It would be great

**Comment by mouse-reeve** [comment]
This has been fixed for a while :)
