### ISSUE TITLE
Open a Dutch community

### ISSUE THREAD

**Issue by gkraaijeveld** [bookwyrm-social/join-bookwyrm#63]
Hi since the registration is closed, I was thinking that it might be possible to open a Dutch community. Would that be possible?

**Comment by mouse-reeve** [comment]
Yeah! If you'd like to do the admin work of running the instance, you can follow the [installation instructions](https://docs.joinbookwyrm.com/install-prod.html). If you'd like to have managed hosting, where you don't have to do any of the technical work, there's more info on that on [Patreon](https://www.patreon.com/posts/64768354).

**Comment by mouse-reeve** [comment]
I'm closing this because it isn't an actionable issue for this codebase. Please feel free to reach out if you have any other questions ❤️
