### ISSUE TITLE
add instance https://books.birdsonbicycles.racing/

### ISSUE THREAD

**Issue by thrillfall** [bookwyrm-social/join-bookwyrm#64]
I'd like to add my instance at https://books.birdsonbicycles.racing/

I'd like this to be about (hard) SciFi and space opera. But since there are not that many instances yet everything else (but right wing "literature") is very welcome.

Since I don't want to pay for an email provider i'd do invites only? Is that OK?

**Comment by mouse-reeve** [comment]
Yay! I love to add an instance to the list :)

There are free options for email providers like sendgrid, which I'd recommend checking out before going without email entirely -- you can send out invites yourself, but the forgot password utility relies on emailing as well.

**Comment by thrillfall** [comment]
@mouse-reeve why was my instance dropped from your list?

**Comment by mouse-reeve** [comment]
Sorry about that! It was down when I last updated the list. It'll be back on the list this evening

**Comment by thrillfall** [comment]
Thanks!
