### ISSUE TITLE
Add instance Velha Estante

### ISSUE THREAD

**Issue by coffeverton** [bookwyrm-social/join-bookwyrm#65]
Hi!
We are a portuguese instance of Bookwyrm, and we are open to new registrations!

Can you please add us to your instance list?
Our address is https://velhaestante.com.br
Thanks!

**Comment by mouse-reeve** [comment]
Heck yeah! Will do :)

**Comment by coffeverton** [comment]
Hey, our instance is no longer shown on the list... can you please add again?
Thanks!

**Comment by mouse-reeve** [comment]
It hasn't been removed from the list, but the site automatically re-checks the instances every day, and doesn't list them if it can't connect. In most cases, there was a timeout or transient error connecting and it will be re-added the next day
