### ISSUE TITLE
Change default sort order for instance list

### ISSUE THREAD

**Issue by mouse-reeve** [bookwyrm-social/join-bookwyrm#82]
Right now, the list of instances load, by default, in order of when I added the instance to the page, and you can use a javascript sort to change that if you want. But that seems like, possibly, not the optimal way to order the instance list. It could deprioritize closed and invite-only instances, sort by users, or idk, something else? I'd love to get thoughts on this from other folks.

**Comment by jaschaurbach** [comment]
I would deprioritize closed and invite only instances.

**Comment by mouse-reeve** [comment]
from bechorin on matrix: "I think you would want an order that prioritises the best experience for new users. So lots of users (at least while reviews aren't federated per-book), been around longer (less chance of instance shutting down), de-prioritise closed/invite only instances. Can you detect the version? Could prioritise up-to-date instances over out-of-date as a sign it's being maintained. Some weighted score calculated from a range of criteria? "
